### ISSUE TITLE
Unified error handling issues with server interfaces

### ISSUE THREAD

**Issue by xuyifeiOnly** [denvudd/breadit-project.github.io#32]
When I was writing the server API using nextjs, I found that every server that handles routing needs to use try catch to handle errors. I wonder if there is a middleware like koa that can capture all service runtime errors and handle them uniformly?

**Comment by denvudd** [comment]
Hi there!
I'm not entirely sure about this, as I'm still in the process of learning Next.js version 13 and API Routes, but I haven't found a similar approach in the official Next.js documentation or somewhere else.
I believe the only current way to handle errors is to use a try-catch for each route as you said. Similar behavior that you mentioned exists with regular routes, where a common middleware is created (in my project, it's used for user validation). Maybe it's possible that there are some tricks to achieve what you're talking about (but I think such behavior simply doesn't exist yet).

**Comment by xuyifeiOnly** [comment]
Okay, thank you for your answer. I have been learning and I hope to find a global error interception method that can save a lot of judgment logic

**Comment by denvudd** [comment]
Good luck buddy! Let me know if you find something :)
